#!/usr/bin/env python3
"""Generate a ready-to-run airfoil SCENE from plain numbers on the command
line — NACA code (or any .dat), angle of attack, Reynolds number, resolution
and render preset. The units system does the physics; you never touch tau.

    # NACA 4412 at Re = 50,000, 6 deg, dye footage, the accurate solver
    python scripts/make_airfoil_scene.py --naca 4412 --re 50000 --alpha 6 \
           --preset dye

    # a symmetric section, high angle, coarse and fast (fused-friendly)
    python scripts/make_airfoil_scene.py --naca 0012 --re 8000 --alpha 14 \
           --chord-cells 200 --fast --name naca0012_stall

    # use an airfoil you downloaded (Selig .dat from airfoiltools.com)
    python scripts/make_airfoil_scene.py --dat assets/ag16.dat --re 30000 \
           --alpha 3 --name ag16_re30k

What it does, in order:
  1. velocity_ms = Re * nu / chord_m         (Reynolds sets the wind speed)
  2. resolve the lattice through lbm.units — auto-enabling the Smagorinsky
     model if (and only if) the bare tau would fall below the BGK floor.
     If the scene is physically un-simulable (u_lat too high, or tau below
     even the SGS floor) it REFUSES and tells you the fix, exactly like a
     hand-written scene would.
  3. generate the NACA .dat if you passed --naca and it isn't on disk yet.
  4. write scenes/<name>.yaml and re-load it to prove it's valid, then
     print the resolved unit report and the exact run command.

Units discipline is preserved: this only ever hands lbm.units the physical
side plus (cells, u_lat); tau and the wind speed are DERIVED, never typed.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lbm.units import AIR_NU, UnitError, resolve          # noqa: E402
from scripts.make_naca import naca4                        # noqa: E402


def build_yaml(args, velocity_ms: float, sgs: bool, dat_file: str,
               zoom: list[float]) -> str:
    """Render the scene file text. Kept as a template (not yaml.dump) so the
    output reads like the hand-written scenes: comments, grouping, order."""
    accurate = not args.fast
    cx, cy = args.center
    lines = [
        f"# {args.name}: generated by scripts/make_airfoil_scene.py",
        f"# NACA/dat = {dat_file}, alpha = {args.alpha} deg, "
        f"Re = {args.re:g}.",
        f"# velocity_ms = Re*nu/chord = {velocity_ms:.6g} m/s (DERIVED, "
        f"not typed).",
        "# Reproduce/adjust: re-run the generator, or edit alpha_deg /",
        "# physical.velocity_ms here (keep the Reynolds comment honest).",
        f"name: {args.name}",
        "description: >",
        f"  NACA/dat {Path(dat_file).name}, chord {args.chord_cells} cells, "
        f"Re = {args.re:g}, alpha {args.alpha} deg.",
        "",
        "physical:",
        f"  char_length_m: {args.chord_m}       # chord c [m]",
        f"  velocity_ms: {velocity_ms:.6g}       # U = Re*nu/c  ->  "
        f"Re = {args.re:g}",
        f"  nu_m2s: {args.nu:g}",
        "",
        "lattice:",
        f"  cells_per_char: {args.chord_cells}       # chord resolution "
        "(the accuracy dial)",
        f"  u_lat: {args.u_lat:g}               # lattice speed (<= 0.1)",
        "",
        "domain:",
        f"  length_chars: {args.domain[0]:g}",
        f"  height_chars: {args.domain[1]:g}",
        "",
        f"sgs: {'true' if sgs else 'false'}"
        + ("              # auto-enabled: bare tau below the BGK floor"
           if sgs else "             # bare tau clears the BGK floor"),
    ]
    if accurate:
        lines.append("collision: trt              # Phase 8 accurate path "
                     "(pins the wall)")
    lines += [
        "",
        "boundaries:",
        "  inlet: equilibrium_ramp",
        "  outlet: pressure_sponge",
        "  top_bottom: periodic",
        "  ramp_steps: 2000",
        "  sponge_fraction: 0.08",
        "",
        "obstacle:",
        "  type: airfoil_dat",
        f"  dat_file: {dat_file}",
        f"  alpha_deg: {args.alpha}",
        f"  center_x_chars: {cx:g}",
        f"  center_y_chars: {cy:g}",
        "  edge_supersample: 4",
    ]
    if accurate:
        lines.append("  curved_bc: true           # Phase 8 Bouzidi "
                     "interpolated walls")
    lines += [
        "",
        "render:",
        f"  preset: {args.preset}",
        f"  zoom: [{zoom[0]:g}, {zoom[1]:g}, {zoom[2]:g}, {zoom[3]:g}]",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Then: python run.py --scene <name> --seed 1 --steps 0  "
               "(dry run), then drop --steps 0 for the real run.")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--naca", metavar="CODE",
                     help="4-digit NACA code, e.g. 4412 (geometry generated)")
    src.add_argument("--dat", metavar="FILE",
                     help="path to an existing Selig .dat airfoil")
    ap.add_argument("--re", type=float, required=True,
                    help="Reynolds number U*c/nu (sets the wind speed)")
    ap.add_argument("--alpha", type=float, default=4.0,
                    help="angle of attack [deg] (default 4)")
    ap.add_argument("--chord-cells", type=int, default=256,
                    help="cells across the chord: the resolution dial "
                         "(default 256; >= 400 for quantitative work)")
    ap.add_argument("--u-lat", type=float, default=0.05,
                    help="lattice velocity, <= 0.1 (default 0.05; low "
                         "because separated flow amplifies local speed)")
    ap.add_argument("--chord-m", type=float, default=0.1,
                    help="physical chord [m] (default 0.1; only scales units)")
    ap.add_argument("--nu", type=float, default=AIR_NU,
                    help=f"kinematic viscosity [m^2/s] (default air {AIR_NU})")
    ap.add_argument("--domain", type=float, nargs=2, metavar=("LEN", "HGT"),
                    default=[8.0, 5.0],
                    help="tunnel length x height in chords (default 8 5)")
    ap.add_argument("--center", type=float, nargs=2, metavar=("CX", "CY"),
                    default=[2.0, 2.5],
                    help="leading-edge-region placement in chords "
                         "(default 2.0 2.5)")
    ap.add_argument("--preset", default="vorticity",
                    choices=["vorticity", "speed", "dye", "streaklines"],
                    help="render style baked into the scene (default "
                         "vorticity; override at run time with --preset)")
    ap.add_argument("--zoom", type=float, nargs=4,
                    metavar=("X0", "Y0", "X1", "Y1"),
                    help="camera crop in chords (default frames airfoil+wake)")
    ap.add_argument("--sgs", choices=["auto", "on", "off"], default="auto",
                    help="Smagorinsky LES: auto (enable iff needed), on, off")
    ap.add_argument("--fast", action="store_true",
                    help="omit the accurate keys (collision/curved_bc) so the "
                         "fused Triton solver can run it; default is accurate")
    ap.add_argument("--points", type=int, default=120,
                    help="points/surface when generating NACA geometry")
    ap.add_argument("--name", default=None,
                    help="scene name / filename stem (default auto)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing scene file")
    args = ap.parse_args()

    # -- geometry: generate NACA on demand, or use the given .dat -----------
    if args.naca:
        if len(args.naca) != 4 or not args.naca.isdigit():
            ap.error("--naca must be 4 digits, e.g. 4412")
        dat_path = Path("assets") / f"naca{args.naca}.dat"
        if not (REPO / dat_path).exists():
            pts = naca4(args.naca, args.points)
            text = [f"NACA {args.naca} (generated, {args.points} pts/surface, "
                    "closed TE)"]
            text += [f" {x:.6f}  {y:+.6f}" for x, y in pts]
            (REPO / dat_path).write_text("\n".join(text) + "\n",
                                         encoding="ascii")
            print(f"geometry: wrote {dat_path} ({len(pts)} points)")
        else:
            print(f"geometry: reusing existing {dat_path}")
        dat_file = str(dat_path).replace("\\", "/")
    else:
        dat_path = Path(args.dat)
        if not dat_path.exists() and not (REPO / dat_path).exists():
            ap.error(f"--dat file not found: {args.dat}")
        dat_file = str(args.dat).replace("\\", "/")

    if args.name is None:
        base = f"naca{args.naca}" if args.naca else dat_path.stem
        a = str(args.alpha).replace('.', 'p').replace('-', 'm')
        args.name = f"{base}_a{a}_re{args.re:g}"

    # -- physics: Reynolds sets the wind speed; units solve the rest --------
    velocity_ms = args.re * args.nu / args.chord_m

    def try_resolve(sgs: bool):
        return resolve(length_m=args.chord_m, velocity_ms=velocity_ms,
                       nu_m2s=args.nu, cells=args.chord_cells,
                       u_lat=args.u_lat, sgs=sgs)

    if args.sgs == "on":
        sgs = True
    elif args.sgs == "off":
        sgs = False
    else:                                   # auto: enable iff bare BGK refuses
        try:
            try_resolve(sgs=False)
            sgs = False
        except UnitError:
            sgs = True
    try:
        units = try_resolve(sgs=sgs)
    except UnitError as e:
        print(f"\nREFUSED: {e}", file=sys.stderr)
        print("\nThe scene was NOT written. Change a number above (usually: "
              "raise --chord-cells, or --u-lat up to 0.1) and try again.",
              file=sys.stderr)
        return 2

    # -- default camera: frame the airfoil and its near wake ---------------
    cx, cy = args.center
    zoom = args.zoom or [max(0.0, cx - 1.0), max(0.0, cy - 1.5),
                         cx + 4.0, cy + 1.5]

    out = REPO / "scenes" / f"{args.name}.yaml"
    if out.exists() and not args.force:
        print(f"\nREFUSED: scenes/{args.name}.yaml exists (use --force or "
              "--name).", file=sys.stderr)
        return 2
    out.write_text(build_yaml(args, velocity_ms, sgs, dat_file, zoom),
                   encoding="utf-8")

    # -- prove it loads, then show the report and the run line -------------
    from lbm.config import load_scene
    scene = load_scene(args.name)
    print(f"\nwrote scenes/{args.name}.yaml")
    print(scene.report())
    solver = "reference (accurate: TRT + Bouzidi)" if not args.fast \
        else "fused  (fast: BGK + staircase)"
    fused = " --solver fused" if args.fast else ""
    print(f"\n  render     preset={args.preset}  solver={solver}")
    print("\nnext:")
    print(f"  python run.py --scene {args.name} --seed 1 --steps 0"
          "        # dry run (check Re/grid/tau)")
    print(f"  python run.py --scene {args.name} --seed 1 --steps 60000 "
          f"--frame-every 100{fused}")
    print(f"  python scripts/make_video.py out/{args.name}-seed1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
