#!/usr/bin/env python3
"""Generate the 3D planned-scenes table (mirrors scripts/scene_table.py).

Resolves every scene in scenes3d/ through the shared units discipline and
writes notes/scene_table_3d.md. Scenes with sgs: true are re-resolved with
sgs off to document that the plain-BGK guard rail refuses them.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lbm3d.config import list_scenes, load_scene  # noqa: E402
from lbm.units import UnitError, resolve  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "notes" / "scene_table_3d.md"

HEADER = (
    "| scene | Re | L [m] | U [m/s] | cells/L | grid | cells | f-VRAM [GB] "
    "| u_lat | tau | Ma | dx [m] | dt [s] | steps per L/U | status |\n"
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n"
)


def status_for(scene) -> str:
    if not scene.units.sgs:
        return "OK (plain BGK)"
    try:
        resolve(
            scene.units.length_m, scene.units.velocity_ms, scene.units.nu_m2s,
            cells=scene.units.cells, u_lat=scene.units.u_lat, sgs=False,
        )
        return "OK (SGS flagged but not needed)"
    except UnitError:
        return (
            f"needs SGS: bare tau = {scene.units.tau:.4f} "
            "< 0.55, refused by plain-BGK rail"
        )


def main() -> int:
    rows = []
    for name in list_scenes():
        s = load_scene(name)
        u = s.units
        rows.append(
            f"| {s.name} | {u.reynolds:g} | {u.length_m:g} | {u.velocity_ms:g} "
            f"| {u.cells:g} | {s.nx} x {s.ny} x {s.nz} | {s.cells / 1e6:.2f}M "
            f"| {s.vram_gb:.2f} | {u.u_lat:g} | {u.tau:.4g} "
            f"| {u.mach:.3f} | {u.dx_m:.4g} | {u.dt_s:.4g} "
            f"| {u.steps_per_char_time:.0f} | {status_for(s)} |"
        )

    table = "# Planned 3D scenes — resolved lattice parameters (D3Q19)\n\n"
    table += "Generated by scripts/scene_table3d.py; all values come out of "
    table += "lbm/units.py (shared with 2D — the Reynolds triangle is\n"
    table += "dimension-blind), none set by hand. f-VRAM is the fp32 A-B\n"
    table += "population working set (152 B/cell) on the 16 GB card.\n\n"
    table += HEADER + "\n".join(rows) + "\n"

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(table, encoding="utf-8")
    print(table)
    print(f"written to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
